/*=========================================================================

  Program:   Visualization Toolkit
  Module:    vtkMeanBlurImageFilter.h

  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  All rights reserved.
  See Copyright.txt or http://www.kitware.com/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notice for more information.

=========================================================================*/
// .NAME vtkGaussianBlurImageFilter - peforms Gaussian blurring of an input image
// .SECTION Description
// vtkMyImageShiftFilter is a filter to generate scalar values from a
// dataset.  The scalar values lie within a user specified range, and
// are generated by computing a projection of each dataset point onto
// a line. The line can be oriented arbitrarily. A typical example is
// to generate scalars based on elevation or height above a plane.

#ifndef __vtkMeanImageFilter_h
#define __vtkMeanImageFilter_h

#include <vtkITKImageFilter.h>

#include <itkMeanImageFilter.h>

class VTK_EXPORT vtkMeanImageFilter : public vtkITKImageFilter
{
public:

  static vtkMeanImageFilter* New();
  vtkTypeMacro(vtkMeanImageFilter, vtkITKImageFilter);
  void PrintSelf(ostream& os, vtkIndent indent);

  //BTX
  typedef Superclass::PixelType             PixelType;
  typedef Superclass::ITKImageType          ITKImageType;
  typedef Superclass::ITKInternalFilterType ITKInternalFilterType;
  typedef Superclass::ITKImageImportType    ITKImageImportType;
  typedef Superclass::ITKImageExportType    ITKImageExportType;
  typedef itk::MeanImageFilter< ITKImageType, ITKImageType >
    ITKMeanFilterType;
  //ETX

  vtkSetVector3Macro(NeighborhoodRadius, int);
  vtkGetVector3Macro(NeighborhoodRadius, int);

protected:
  vtkMeanImageFilter();
  ~vtkMeanImageFilter();

  int NeighborhoodRadius[3];

  //BTX
  ITKMeanFilterType::Pointer MeanFilter;
  //ETX

protected:
  int UpdateInternalFilters();

private:
  vtkMeanImageFilter(const vtkMeanImageFilter&);  // Not implemented.
  void operator=(const vtkMeanImageFilter&);  // Not implemented.
};

#endif
