/*=========================================================================

  Program:   Visualization Toolkit
  Module:    vtkDeconvolutionImageFilter.h

  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  All rights reserved.
  See Copyright.txt or http://www.kitware.com/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notice for more information.

=========================================================================*/
// .NAME vtkDeconvolutionImageFilter - peforms Gaussian blurring of an input image
// .SECTION Description
// vtkMyImageShiftFilter is a filter to generate scalar values from a
// dataset.  The scalar values lie within a user specified range, and
// are generated by computing a projection of each dataset point onto
// a line. The line can be oriented arbitrarily. A typical example is
// to generate scalars based on elevation or height above a plane.

#ifndef __vtkDeconvolutionImageFilter_h
#define __vtkDeconvolutionImageFilter_h

#include <vtkITKImageFilter.h>

class VTK_EXPORT vtkDeconvolutionImageFilter : public vtkITKImageFilter
{
public:

  static vtkDeconvolutionImageFilter* New();
  vtkTypeMacro(vtkDeconvolutionImageFilter, vtkITKImageFilter);
  void PrintSelf(ostream& os, vtkIndent indent);

  //BTX
  typedef Superclass::PixelType             PixelType;
  typedef Superclass::ITKImageType          ITKImageType;
  typedef Superclass::ITKInternalFilterType ITKInternalFilterType;
  typedef Superclass::ITKImageImportType    ITKImageImportType;
  typedef Superclass::ITKImageExportType    ITKImageExportType;
  //ETX

  // Set the convolution kernel image
  void SetKernelImage(vtkAlgorithmOutput* image);

  // Set/get the image padding type
  vtkSetMacro(PaddingMethod, int);
  vtkGetMacro(PaddingMethod, int);

protected:
  vtkDeconvolutionImageFilter();
  ~vtkDeconvolutionImageFilter();

  int PaddingMethod;

protected:
  virtual int RequestUpdateExtent (vtkInformation *, vtkInformationVector **, vtkInformationVector *);

  virtual int FillInputPortInformation(int port, vtkInformation *info);

private:
  vtkDeconvolutionImageFilter(const vtkDeconvolutionImageFilter&);  // Not implemented.
  void operator=(const vtkDeconvolutionImageFilter&);  // Not implemented.
};

#endif
