/*=========================================================================

  Program:   Visualization Toolkit
  Module:    vtkGaussianImageSource.h

  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  All rights reserved.
  See Copyright.txt or http://www.kitware.com/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notice for more information.

=========================================================================*/
// .NAME vtkGaussianImageSource - peforms Gaussian blurring of an input image
// .SECTION Description
// vtkMyImageShiftFilter is a filter to generate scalar values from a
// dataset.  The scalar values lie within a user specified range, and
// are generated by computing a projection of each dataset point onto
// a line. The line can be oriented arbitrarily. A typical example is
// to generate scalars based on elevation or height above a plane.

#ifndef __vtkGaussianImageSource_h
#define __vtkGaussianImageSource_h

#include <vtkImageAlgorithm.h>

#include <itkVTKImageImport.h>
#include <itkVTKImageExport.h>
#include <itkGaussianImageSource.h>

class vtkImageExport;
class vtkImageImport;

class VTK_EXPORT vtkGaussianImageSource : public vtkImageAlgorithm
{
public:

  //BTX
  typedef float
    PixelType;
  typedef itk::Image< PixelType, 3 >
    ITKImageType;
  typedef itk::VTKImageImport< ITKImageType >
    ITKImageImportType;
  typedef itk::VTKImageExport< ITKImageType >
    ITKImageExportType;
  typedef itk::GaussianImageSource< ITKImageType >
    ITKGaussianSourceType;
  //ETX

  static vtkGaussianImageSource* New();
  vtkTypeMacro(vtkGaussianImageSource, vtkImageAlgorithm);
  void PrintSelf(ostream& os, vtkIndent indent);

  // Set/get image size.
  vtkSetVector3Macro(Size, int);
  vtkGetVector3Macro(Size, int);

  // Set/get standard deviation of the Gaussian.
  vtkSetVector3Macro(StandardDeviation, double);
  vtkGetVector3Macro(StandardDeviation, double);

protected:
  vtkGaussianImageSource();
  ~vtkGaussianImageSource();

  int    Size[3];
  double StandardDeviation[3];

  //BTX
  ITKGaussianSourceType::Pointer GaussianSource;
  ITKImageExportType::Pointer    ITKExporter;
  //ETX
  vtkImageImport*                VTKImporter;

protected:
  void InitializeITKImporter();
  void InitializeITKExporter();

  int RequestData(vtkInformation *request, vtkInformationVector **inputVector, vtkInformationVector *outputVector);

  //BTX
  template <class T>
  void RunITKPipeline(const T *input);
  //ETX

private:
  vtkGaussianImageSource(const vtkGaussianImageSource&);  // Not implemented.
  void operator=(const vtkGaussianImageSource&);  // Not implemented.
};

#endif
