/*=========================================================================

  Program:   Visualization Toolkit
  Module:    vtkGaussianBlurImageFilter.h

  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  All rights reserved.
  See Copyright.txt or http://www.kitware.com/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notice for more information.

=========================================================================*/
// .NAME vtkGaussianBlurImageFilter - peforms Gaussian blurring of an input image
// .SECTION Description
// vtkMyImageShiftFilter is a filter to generate scalar values from a
// dataset.  The scalar values lie within a user specified range, and
// are generated by computing a projection of each dataset point onto
// a line. The line can be oriented arbitrarily. A typical example is
// to generate scalars based on elevation or height above a plane.

#ifndef __vtkLaplacianOfGaussianFilter_h
#define __vtkLaplacianOfGaussianFilter_h

#include <vtkITKImageFilter.h>

#include <itkLaplacianRecursiveGaussianImageFilter.h>

class VTK_EXPORT vtkLaplacianOfGaussianFilter : public vtkITKImageFilter
{
public:

  static vtkLaplacianOfGaussianFilter* New();
  vtkTypeMacro(vtkLaplacianOfGaussianFilter, vtkITKImageFilter);
  void PrintSelf(ostream& os, vtkIndent indent);

  //BTX
  typedef Superclass::PixelType             PixelType;
  typedef Superclass::ITKImageType          ITKImageType;
  typedef Superclass::ITKInternalFilterType ITKInternalFilterType;
  typedef Superclass::ITKImageImportType    ITKImageImportType;
  typedef Superclass::ITKImageExportType    ITKImageExportType;
  typedef itk::LaplacianRecursiveGaussianImageFilter< ITKImageType, ITKImageType >
    ITKLOGFilterType;
  //ETX

  vtkSetMacro(Sigma, double);
  vtkGetMacro(Sigma, double);

protected:
  vtkLaplacianOfGaussianFilter();
  ~vtkLaplacianOfGaussianFilter();

  double Sigma;

  //BTX
  ITKLOGFilterType::Pointer		 LOGFilter;
  //ETX

protected:
  int UpdateInternalFilters();

private:
  vtkLaplacianOfGaussianFilter(const vtkLaplacianOfGaussianFilter&);  // Not implemented.
  void operator=(const vtkLaplacianOfGaussianFilter&);  // Not implemented.
};

#endif
